version: '3.9'
services:
  vue:
    image: 'node:15.12.0-buster'
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - '${VUE_APP_PORT:-8080}:8080'
    networks:
      - sail
    entrypoint: 'bash -c "npm install -d && npm run serve -d"'
    healthcheck:
      test: 'curl localhost:8080'

networks:
  sail:
    external:
      name: dev-exam-backend_sail